= Greedy Algorithms

== Outcomes

- Explain how greedy algorithms are used to develop algorithms
- Solve problems by creatively applying greedy techniques
- Communicate algorithmic ideas at different abstraction levels
- Evaluate the efficiency of algorithms and justify their correctness. (The hard part)

== The algorithm

- Doesn't always work, and there is no simple rule to determine whether a greedy algorithm works and is optimal.

- Greedy algorithms work on some problems in P, but they do not work on NP-hard problems.

/ P: Problems that can be solved in polynomial time.
/ NP: Problems that can be checked in polynomial time.

=== What is a greedy algorithm

A greedy algorithm is one that solves a problem by dividing it into stages, and rather than exhaustively searching all the ways to get from one stage to the next, instead only consideres the choice that appears best.

Looks for the best short term solution which reduces search space to decrease time complexity.

However, this means that you need to prove that the locally optimal choice leads to the globally optimal outcome.

/ Matroids: Is a framework to determine whether a problem can be solved with a greedy algorithm, not covered in COMP3121.

=== Proving a Greedy Algorithm

There are two main methods of proving a greedy algorithm:
- *Greedy stays ahead*: \
  Proves that at every stage, no other sequence of choices could do better than our proposed algorithm. Usually uses induction in the proof.
- *Exchange argument*: \
  Consider an alternative solution, and gradually transform it to the solution found by our proposed algorithm without making it any worse. Usually a proof by contradiction.

Types of greedy problems:
- *Optimal Selection*
- *Optimal Ordering*
- *Optimal Merging*

#pagebreak()

==== Greedy stays ahead

+ *Label your algorithm's partial solutions, and a general solution* e.g \
  Let $A = {a_1, a_2, ..., a_k}$ be the solution generated by your algorithm, with elements appearing in the order they are added. Let $O = {o_1, o_2, ..., o_k}$ be an arbitrary (or optimal) feasible solution. Ordering of $O$ is generally similar to the ordering of $A$.

+ *Find a measure* \
  Define a _measure_ $f(dot)$ by which greedy stays ahead of a general / optimal solution. e.g. $f(a_1, ..., a_j)$ might be the last completion time of the first $j$ jobs.

+ *Prove greedy stays ahead (the Inductive step)* \
  Show that the partial solutions constructed by greedy are always just as good as the initial segments of your other solution, based on the measure you selected.
  - For all indices $r <= k$, prove by induction that $f(a_1, ..., a_r)[>=, <=]f(o_1, ..., o_r)$.

==== Exchange Argument
